SELECT 'COMPRAS' TIPO, COUNT(*) DOCUMENTOS, SUM(d.CANTIDAD * d.PRECIO) TOTAL
FROM COMPRA c JOIN DETALLE_COMPRA d ON d.COMPRA_ID=c.ID
UNION ALL
SELECT 'VENTAS', COUNT(DISTINCT v.ID), SUM(d.CANTIDAD * d.PRECIO)
FROM VENTA v JOIN DETALLE_VENTA d ON d.VENTA_ID=v.ID;

SELECT m.NOMBRE METODO_PAGO, COUNT(*) VENTAS
FROM VENTA v JOIN METODOPAGO m ON m.ID=v.METODOPAGO_ID
GROUP BY m.NOMBRE ORDER BY m.NOMBRE;
