SELECT 'STOCK_NEGATIVO' CONTROL, COUNT(*) INCIDENCIAS FROM PRODUCTO WHERE STOCK < 0 UNION ALL
SELECT 'COMPRA_SIN_DETALLE', COUNT(*) FROM COMPRA c WHERE NOT EXISTS (SELECT 1 FROM DETALLE_COMPRA d WHERE d.COMPRA_ID=c.ID) UNION ALL
SELECT 'VENTA_SIN_DETALLE', COUNT(*) FROM VENTA v WHERE NOT EXISTS (SELECT 1 FROM DETALLE_VENTA d WHERE d.VENTA_ID=v.ID) UNION ALL
SELECT 'PRODUCTO_SIN_CATEGORIA', COUNT(*) FROM PRODUCTO p LEFT JOIN CATEGORIAPRODUCTO c ON c.ID=p.CATEGORIA_ID WHERE c.ID IS NULL UNION ALL
SELECT 'PRODUCTO_SIN_MARCA', COUNT(*) FROM PRODUCTO p LEFT JOIN MARCA m ON m.ID=p.MARCA_ID WHERE m.ID IS NULL UNION ALL
SELECT 'USUARIO_SIN_EMPLEADO', COUNT(*) FROM USUARIOSISTEMA u LEFT JOIN EMPLEADO e ON e.ID=u.EMPLEADO_ID WHERE e.ID IS NULL UNION ALL
SELECT 'DNI_CLIENTE_DUPLICADO', COUNT(*) FROM (SELECT DNI FROM CLIENTE GROUP BY DNI HAVING COUNT(*) > 1) UNION ALL
SELECT 'RUC_PROVEEDOR_DUPLICADO', COUNT(*) FROM (SELECT RUC FROM PROVEEDOR GROUP BY RUC HAVING COUNT(*) > 1) UNION ALL
SELECT 'USERNAME_DUPLICADO', COUNT(*) FROM (SELECT USERNAME FROM USUARIOSISTEMA GROUP BY USERNAME HAVING COUNT(*) > 1);
