SELECT 'EMPLEADO_CARGO' CONTROL, COUNT(*) HUERFANOS
FROM EMPLEADO e LEFT JOIN CARGO c ON c.ID=e.CARGO_ID WHERE c.ID IS NULL UNION ALL
SELECT 'PRODUCTO_CATEGORIA', COUNT(*)
FROM PRODUCTO p LEFT JOIN CATEGORIAPRODUCTO c ON c.ID=p.CATEGORIA_ID WHERE c.ID IS NULL UNION ALL
SELECT 'PRODUCTO_MARCA', COUNT(*)
FROM PRODUCTO p LEFT JOIN MARCA m ON m.ID=p.MARCA_ID WHERE m.ID IS NULL UNION ALL
SELECT 'USUARIO_EMPLEADO', COUNT(*)
FROM USUARIOSISTEMA u LEFT JOIN EMPLEADO e ON e.ID=u.EMPLEADO_ID WHERE e.ID IS NULL UNION ALL
SELECT 'USUARIO_ROL', COUNT(*)
FROM USUARIOROL ur LEFT JOIN USUARIOSISTEMA u ON u.ID=ur.USUARIO_ID
LEFT JOIN ROL r ON r.ID=ur.ROL_ID WHERE u.ID IS NULL OR r.ID IS NULL UNION ALL
SELECT 'DETALLE_VENTA', COUNT(*)
FROM DETALLE_VENTA d LEFT JOIN VENTA v ON v.ID=d.VENTA_ID
LEFT JOIN PRODUCTO p ON p.ID=d.PRODUCTO_ID WHERE v.ID IS NULL OR p.ID IS NULL;
