SELECT 'CARGO' TABLA, COUNT(*) FILAS FROM CARGO UNION ALL
SELECT 'CATEGORIAPRODUCTO', COUNT(*) FROM CATEGORIAPRODUCTO UNION ALL
SELECT 'CLIENTE', COUNT(*) FROM CLIENTE UNION ALL
SELECT 'COMPRA', COUNT(*) FROM COMPRA UNION ALL
SELECT 'DETALLE_COMPRA', COUNT(*) FROM DETALLE_COMPRA UNION ALL
SELECT 'EMPLEADO', COUNT(*) FROM EMPLEADO UNION ALL
SELECT 'MARCA', COUNT(*) FROM MARCA UNION ALL
SELECT 'METODOPAGO', COUNT(*) FROM METODOPAGO UNION ALL
SELECT 'PRODUCTO', COUNT(*) FROM PRODUCTO UNION ALL
SELECT 'PROVEEDOR', COUNT(*) FROM PROVEEDOR UNION ALL
SELECT 'ROL', COUNT(*) FROM ROL UNION ALL
SELECT 'USUARIOROL', COUNT(*) FROM USUARIOROL UNION ALL
SELECT 'USUARIOSISTEMA', COUNT(*) FROM USUARIOSISTEMA UNION ALL
SELECT 'VENTA', COUNT(*) FROM VENTA UNION ALL
SELECT 'DETALLE_VENTA', COUNT(*) FROM DETALLE_VENTA;
