SELECT COUNT(*) PRODUCTOS_SIN_CONCILIAR
FROM PRODUCTO p
WHERE p.STOCK <> 20
  + COALESCE((SELECT SUM(dc.CANTIDAD) FROM DETALLE_COMPRA dc WHERE dc.PRODUCTO_ID=p.ID), 0)
  - COALESCE((SELECT SUM(dv.CANTIDAD) FROM DETALLE_VENTA dv WHERE dv.PRODUCTO_ID=p.ID), 0);

SELECT COUNT(*) STOCK_NEGATIVO FROM PRODUCTO WHERE STOCK < 0;
