SELECT 'PRODUCTO_NOMBRE' CONTROL, COUNT(*) GRUPOS_DUPLICADOS FROM (
  SELECT LOWER(TRIM(NOMBRE)) FROM PRODUCTO GROUP BY LOWER(TRIM(NOMBRE)) HAVING COUNT(*) > 1
) UNION ALL
SELECT 'CLIENTE_DNI', COUNT(*) FROM (
  SELECT DNI FROM CLIENTE GROUP BY DNI HAVING COUNT(*) > 1
) UNION ALL
SELECT 'CLIENTE_CORREO', COUNT(*) FROM (
  SELECT LOWER(TRIM(CORREO)) FROM CLIENTE WHERE CORREO IS NOT NULL
  GROUP BY LOWER(TRIM(CORREO)) HAVING COUNT(*) > 1
) UNION ALL
SELECT 'PROVEEDOR_RUC', COUNT(*) FROM (
  SELECT RUC FROM PROVEEDOR GROUP BY RUC HAVING COUNT(*) > 1
) UNION ALL
SELECT 'USUARIO_ROL', COUNT(*) FROM (
  SELECT USUARIO_ID, ROL_ID FROM USUARIOROL GROUP BY USUARIO_ID, ROL_ID HAVING COUNT(*) > 1
);
